const { v4: uuidv4 } = require('uuid');

class LlmClient {
    constructor(config = {}) {
        this.config = {
            provider: config.provider || 'mock',
            apiKey: config.apiKey || process.env.OPENAI_API_KEY,
            model: config.model || 'gpt-4',
            maxTokens: config.maxTokens || 2000,
            temperature: config.temperature || 0.7,
            ...config
        };
        
        this.isMockMode = !config.apiKey && !process.env.OPENAI_API_KEY;
        this.client = null;
    }

    async initialize() {
        if (this.isMockMode) {
            console.log('[LlmClient] Running in mock mode');
            return;
        }

        switch (this.config.provider) {
            case 'openai':
                this.client = await this.initOpenAIClient();
                break;
            case 'anthropic':
                this.client = await this.initAnthropicClient();
                break;
            case 'local':
                this.client = await this.initLocalClient();
                break;
            default:
                console.warn(`[LlmClient] Unknown provider: ${this.config.provider}, using mock mode`);
                this.isMockMode = true;
        }
    }

    async initOpenAIClient() {
        try {
            const { Configuration, OpenAIApi } = require('openai');
            const configuration = new Configuration({
                apiKey: this.config.apiKey || process.env.OPENAI_API_KEY
            });
            return new OpenAIApi(configuration);
        } catch (error) {
            console.error('[LlmClient] Failed to initialize OpenAI client:', error.message);
            this.isMockMode = true;
            return null;
        }
    }

    async initAnthropicClient() {
        return {
            provider: 'anthropic',
            async generate(prompt, options) {
                return `Claude response for: ${prompt.substring(0, 50)}...`;
            }
        };
    }

    async initLocalClient() {
        return {
            provider: 'local',
            async generate(prompt, options) {
                return `Local model response for: ${prompt.substring(0, 50)}...`;
            }
        };
    }

    async generate(options) {
        const {
            prompt,
            system = '',
            maxTokens = this.config.maxTokens,
            temperature = this.config.temperature,
            model = this.config.model
        } = options;

        if (this.isMockMode) {
            return this.generateMockResponse(prompt, options);
        }

        try {
            if (this.config.provider === 'openai' && this.client) {
                return await this.generateOpenAI(prompt, system, maxTokens, temperature, model);
            } else if (this.client) {
                return await this.client.generate(prompt, options);
            } else {
                return this.generateMockResponse(prompt, options);
            }
        } catch (error) {
            console.error('[LlmClient] Generation failed, falling back to mock:', error.message);
            return this.generateMockResponse(prompt, options);
        }
    }

    async generateOpenAI(prompt, system, maxTokens, temperature, model) {
        const fullPrompt = system ? `${system}\n\n${prompt}` : prompt;

        const response = await this.client.createCompletion({
            model,
            prompt: fullPrompt,
            max_tokens: maxTokens,
            temperature
        });

        return response.data.choices[0].text.trim();
    }

    generateMockResponse(prompt, options) {
        const task = options.taskType || 'general';
        
        const mockResponses = {
            code: `// Generated game code
class GameScene extends Phaser.Scene {
    constructor() {
        super({ key: 'GameScene' });
    }

    create() {
        const centerX = this.cameras.main.centerX;
        const centerY = this.cameras.main.centerY;
        
        this.add.text(centerX, centerY, 'Game Generated by AI', {
            fontSize: '32px',
            fill: '#fff'
        }).setOrigin(0.5);
        
        console.log('Game initialized successfully');
    }
}

export default GameScene;`,
            
            art: JSON.stringify({
                style: 'pixel_art',
                colorPalette: ['#4a90d9', '#8b5cf6', '#10b981', '#f59e0b'],
                recommendedAssets: [
                    { type: 'player_sprite', size: '64x64', frames: 8 },
                    { type: 'enemy_sprite', size: '48x48', frames: 4 },
                    { type: 'background', size: '1920x1080', layers: 3 }
                ]
            }, null, 2),
            
            design: JSON.stringify({
                gameType: 'action_platformer',
                coreMechanics: ['movement', 'combat', 'collection'],
                progressionSystem: 'level_based',
                economy: { currency: 'gold', items: ['weapon', 'armor', 'potion'] }
            }, null, 2),
            
            qa: JSON.stringify({
                testCases: [
                    { id: 'TC001', feature: 'Player Movement', steps: 5, expectedResult: 'Smooth movement' },
                    { id: 'TC002', feature: 'Collision Detection', steps: 3, expectedResult: 'Proper collision' }
                ],
                riskAssessment: 'low',
                coverage: '85%'
            }, null, 2),
            
            operations: JSON.stringify({
                serverConfig: {
                    maxPlayers: 100,
                    tickRate: 60,
                    region: 'us-west'
                },
                metrics: ['latency', 'fps', 'concurrent_users']
            }, null, 2),
            
            general: `[Mock Response] Received task: ${prompt.substring(0, 100)}...
            
Task processed successfully by multi-agent system.
Estimated completion: 2-5 seconds.
Generated artifacts: 1 file(s).`
        };

        return mockResponses[task] || mockResponses.general;
    }

    async chat(options) {
        const {
            messages,
            system = '',
            maxTokens = this.config.maxTokens,
            temperature = this.config.temperature,
            model = this.config.model
        } = options;

        if (this.isMockMode) {
            return this.generateMockChatResponse(messages);
        }

        try {
            if (this.config.provider === 'openai' && this.client) {
                const fullMessages = system ? [
                    { role: 'system', content: system },
                    ...messages
                ] : messages;

                const response = await this.client.createChatCompletion({
                    model,
                    messages: fullMessages,
                    max_tokens: maxTokens,
                    temperature
                });

                return response.data.choices[0].message.content;
            }
        } catch (error) {
            console.error('[LlmClient] Chat failed:', error.message);
        }

        return this.generateMockChatResponse(messages);
    }

    generateMockChatResponse(messages) {
        const lastMessage = messages[messages.length - 1]?.content || '';
        return `[Mock Chat Response] I received your message: "${lastMessage.substring(0, 50)}..."
        
This is a simulated response from the LLM client running in mock mode.`;
    }

    getStatus() {
        return {
            provider: this.config.provider,
            model: this.config.model,
            isMockMode: this.isMockMode,
            initialized: this.client !== null || this.isMockMode
        };
    }
}

module.exports = { LlmClient };
